[package]
name = "near-light-client-on-eth"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.workspace = true
ethers.workspace = true
tokio.workspace = true
ethereum-types.workspace = true